### ISSUE TITLE
Library fails with fake network devices

### ISSUE THREAD

**Issue by xobs** [jlaine/aioice#6]
I'm running `aiortc` under Ubuntu 16.04 on WSL on Windows 10, and it has the following network interfaces:

````sh
(python) xobs@Cuboid:~$ ip -4 addr
13: eth0: <BROADCAST,MULTICAST,UP> mtu 1500 group default qlen 1
    inet 10.0.240.4/24 brd 10.0.240.255 scope global dynamic
       valid_lft forever preferred_lft forever
3: eth1: <> mtu 1500 group default qlen 1
    inet 169.254.40.162/16 brd 169.254.255.255 scope global dynamic
       valid_lft forever preferred_lft forever
26: eth2: <> mtu 1500 group default qlen 1
    inet 10.0.11.1/24 brd 10.0.11.255 scope global dynamic
       valid_lft forever preferred_lft forever
1: lo: <LOOPBACK,UP> mtu 1500 group default qlen 1
    inet 127.0.0.1/8 brd 127.255.255.255 scope global dynamic
       valid_lft forever preferred_lft forever
(python) xobs@Cuboid:~$
````

In this list, `eth1` is not a real network device, and attempts to bind to it result in errors.  For example, using the `aiortc` example `server`, upon clicking "Start" the following error is printed:

````python
Binding to: ('10.0.240.4', 0)
DEBUG:ice:Connection(0) protocol(0) connection_made(<_SelectorDatagramTransport fd=10 read=idle write=<idle, bufsize=0>>)
Binding to: ('169.254.40.162', 0)
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/mnt/d/Code/alzim/python/lib/python3.5/site-packages/aiohttp/web_protocol.py", line 416, in start
    resp = yield from self._request_handler(request)
  File "/mnt/d/Code/alzim/python/lib/python3.5/site-packages/aiohttp/web.py", line 325, in _handle
    resp = yield from handler(request)
  File "/mnt/d/Code/alzim/python/lib/python3.5/site-packages/aiohttp/web_middlewares.py", line 93, in impl
    return (yield from handler(request))
  File "./server.py", line 167, in offer
    await pc.setLocalDescription(answer)
  File "/mnt/d/Code/alzim/python/lib/python3.5/site-packages/aiortc/rtcpeerconnection.py", line 317, in setLocalDescription
    await self.__gather()
  File "/mnt/d/Code/alzim/python/lib/python3.5/site-packages/aiortc/rtcpeerconnection.py", line 453, in __gather
    await asyncio.gather(*coros)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/mnt/d/Code/alzim/python/lib/python3.5/site-packages/aiortc/rtcicetransport.py", line 150, in gather
    await self._connection.gather_candidates()
  File "/mnt/d/Code/alzim/python/lib/python3.5/site-packages/aioice/ice.py", line 323, in gather_candidates
    addresses=addresses)
  File "/mnt/d/Code/alzim/python/lib/python3.5/site-packages/aioice/ice.py", line 672, in get_component_candidates
    local_addr=(address, 0))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 844, in create_datagram_endpoint
    raise exceptions[0]
  File "/usr/lib/python3.5/asyncio/base_events.py", line 829, in create_datagram_endpoint
    sock.bind(local_address)
OSError: [Errno 99] Cannot assign requested address
````

I have modified `asyncio` to print its address just prior to calling `sock.bind()`, so you can see the address that's causing the issue.

If I simply omit `eth1`, then the example works.  However, as-is, the library doesn't work under WSL.

**Comment by jlaine** [comment]
I didn't quite understand how this device is "fake"? Could you provide some more information and maybe suggest a way to detect such devices?

**Comment by jlaine** [comment]
Looking at the ifconfig output it looks as though the interface isn't flagged as "UP", but in that case I don't understand why you don't have the same issue with eth2?

**Comment by xobs** [comment]
You're right, the only interfaces that are up are eth0 and lo.

I'm not sure what Microsoft uses eth1 (169.254.0.0/16) for, except I'd imagine it has something to do with how they configure Ubuntu inside the VM.  It's not a real network interface, which is why attempting to bind() to it results in an error.

eth2 is a real USB network interface, it's just down.

I'm not sure what can be done here.  Either one of the following:

1. Don't attempt to bind() to network interfaces that aren't up, or
1. Don't abort when bind() fails

**Comment by jlaine** [comment]
If eth2 doesn't give you an error then I think the interface state isn't the issue.

I *think* it's because link-local addresses (for ipv4 169.254.*) need a "scope id" when calling bind. In this case skipping link-local addresses might be the way to go.

**Comment by xobs** [comment]
It could be the link-local thing.  Are there other machines that could be tested?

Here's a quick one-liner example of the problem, testing out all four interfaces on the system:

```sh
(python) xobs@Cuboid:~$ python3 -c 'import socket; socket.socket().bind(("10.0.11.1", 6677))'
(python) xobs@Cuboid:~$ python3 -c 'import socket; socket.socket().bind(("127.0.0.1", 6677))'
(python) xobs@Cuboid:~$ python3 -c 'import socket; socket.socket().bind(("10.0.240.4", 6677))'
(python) xobs@Cuboid:~$ python3 -c 'import socket; socket.socket().bind(("169.254.40.162", 6677))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 99] Cannot assign requested address
(python) xobs@Cuboid:~$
```

**Comment by jlaine** [comment]
I no longer think the address is the problem, I plugged an USB / Ethernet adaptor into my laptop and configured it for use with a link-local address:

```enx002500ed08c9: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 169.254.79.176  netmask 255.255.0.0  broadcast 169.254.255.255```

I then tried your one-liner to bind on that address, and it worked fine:

```$ python3 -c 'import socket; socket.socket().bind(("169.254.79.176", 6677))'
$```

**Comment by jlaine** [comment]
OK, so the bottom line : the only workable option I see is to have a try/catch OSError around the create_datagram_endpoint and skip addresses we cannot bind to.
